fossasia/flappy-svg

- Contributors.md
Sorry I forgot to edit this because just now I read it in GCI task written to add your name.
> GCI task - Added name in Contributors.md file

- javascript/background.js
- javascript/flapping.js
- javascript/layers.js
I implemented a possible solution for 
Use hide and show methods for Flappy and Background #5  issue
> Added hide_layer and show_layer methods for layers

- flappy.svg
Implemented fix to Issue  Formatting/Aligning the text on home/welcome screen #19
> Alligned text on welcome screen

- description/en-us.md
if it is correct, I will start to write it in Spanish.
> Added description

- description/de-de.md
Someone German, please review for correctness as translation of en-us.md
> added German translation

- flappy.svg
- javascript/flapping.js
Hi, I've added a new character, but I am currently unable to claim that task right now as I am still waiting for approval on another one, I will claim it once ready. Do advice on how to improve on the design if possible.
> Added new character "alien"

- Contributors.md
This is as per proposed by @niccokunzmann  in comments of pull request #57
> Adding myself to contributors list

- credits.html
- javascript/links.js
- links.html
Page has the names and links regarding the contributors.
Issue #58 part1 resolved.
> Credit page added

- Contributing.md
The comment is no longer needed.
> Google Code-In comment removed

- javascript/links.js
- links.html
#73  links fixed.
used instances 0/1 as when we visit links.html we keep the instances 1.
when we again visit from android function we make the instances = 0.
@niccokunzmann  
have a look here.
> links in links.html fixed

- credits.html
- index.html
- links.html
For issue #77. Added a title to the index file and fixed the link to the favicon image. Also added favicons to the credits.html and links.html files :blush:
> Added a title to the index.html file & favicons

- flappy.svg
The link.jpg now appears correctly.
> Fixes #79 - missing link image to link.html

- javascript/links.js
- links.html
#73  part 4 also resolved.
@niccokunzmann  please review it. 
And if satisfied you can close issue #73 .
any suggestions is too appreciated.
> back button function handled

- credits.html
- style/credits.css
#62 
issue handled for credits.html
coming up for links.html soon.
> resizing of credits.html handled

- links.html
- style/credits.css
- style/links.css
#62  part 2 of the issue resolved.
links.html resizing handled.
@niccokunzmann  please review and provide feedback.
> resizing handled for links.html 

- flappy.svg
- javascript/flapping.js
- javascript/score.js
In reference to issue #112  I added functions to update score when crossing an obstacle.
> Added a function to Update score

- javascript/flapping.js
In reference to Issue #71  Please check and comment on the status now
> Improved Collision

- main_menu.html
- style/main_menu.css
> Made Mainmenu Responsive

- tasks/add_background/Deutsch.md
- tasks/add_background/English.md
- tasks/add_character/Deutsch.md
- tasks/add_character/English.md
- tasks/add_obstacles/Deutsch.md
- tasks/add_obstacles/English.md
- tasks/implement_improvements/Deutsch.md
- tasks/implement_improvements/English.md
I updated the task descriptions to allow fast merging of student code.
Now, the pr may create new issues that need to be resolved.
> added descriptions for fast merge

- flappy.svg
Added new space background. And two layer rocket(player) and space_rocket(obstacle).
> Added new background layer.

- credits.html
Task:
https://codein.withgoogle.com/dashboard/task-instances/5958125771292672/
Added name in credits for compiling windows installer of FlappySVG.
Check master branch for source and executable.
PR (master branch): https://github.com/fossasia/flappy-svg/pull/132
> Added name in credits.html

- README.md
added download link to windows installer
> fixes #135

- credits.html
- flappy.svg
- javascript/background.js
- javascript/flapping.js
Sorry, as I was testing the game I realised that there was a sizing issue and the obstacles were too large, so I fixed that and added my name to the credits file
> Resized obstacles to fit window and added name in credits

- flappy.svg
created pictures so that the backgrounds can be chosen with related pictures instead of coloured circles.
> choosing diffent background through pictures menu

- javascript/start_screen.js
Resolves issue #131
[Live page](https://baidya99.github.io/flappy-svg/)
> Added button for some backgrounds

- links.html
> Fixed Link to Download dmg file

- javascript/background.js
- javascript/flapping.js
- javascript/levels.js
- javascript/start.js
- javascript/start_screen.js
Resolves #194
Also
-Changed the look of Game Over.
-Added link to help file
-Renamed the obstacle layer 'obstacle' to energy and added a background for it and also the required code.
New
Original
> Added score again

- credits.html
- javascript/flapping.js
- javascript/start.js
- layers/characters/black_cat.svg
This is the task instance: https://codein.withgoogle.com/dashboard/task-instances/6354451176620032/
> Add new character and name to credits

- credits.html
Added myself to the credits.html file, since I have pushed a PR #205 which adds my app to the project.
Done as part of GCI task: https://codein.withgoogle.com/dashboard/task-instances/6293522636341248/
Please review and merge.
> Added myself

- README.md
@niccokunzmann as you have asked for, I have added the info to the readme as to where the app could be downloaded. I do not have write access so made a PR. The app's now hosted on google drive and is available for public
happy coding :)
> Added my app's download link

- FlappySVG_Android_2/app/src/main/java/org/fossasia/www/flappysvg/CentreActivity.java
Updated code, there were some compatibility issues regarding the app, now it's fixed see the previews @niccokunzmann 
Here are some working screenshots:
> Added new code update

- README.md
@niccokunzmann he's this ...
Added the updated link to the readme.md file as requested.
> Added the new link

- credits.html
- javascript/flapping.js
- javascript/start.js
- layers/characters/grandma.svg
Added character "grandma" to the game. See it [here](https://oanarosca.github.io/flappy-svg).
> Added my character to the game

- javascript/start.js
Happy New year Everyone.
And also added the dog in the list of characters.
> fixed the dog layer bug

- javascript/flapping.js
> fixed issue Dog character overlayed #239

- javascript/flapping.js
> Fix text is overflowing from restart button #246

- .travis.yml
Fixes https://github.com/fossasia/flappy-svg/issues/80
> Fixes #80: Added Travis CI and tests

- credits.html
I add myself to the `credits.html` file because I did a little contribution for this GCI task a while ago: https://codein.withgoogle.com/dashboard/task-instances/6589571577937920/
#197  was my PR.
> Add myself to credits

- README.md
> adding travis-ci badge

- javascript/start.js
- layers/characters/Flappyfish.svg
- layers/characters/Santa.svg
- layers/characters/Super_rocket.svg
- layers/characters/alien.svg
- layers/characters/bat.svg
- layers/characters/bird.svg
- layers/characters/dog.svg
- layers/characters/flappydino.svg
- layers/characters/helicopter.svg
- layers/characters/rocket.svg
Fixes #259
- Use it for onclick for all characters
- Minor code refactoring
Signed-off-by: Hemanth Kumar Veeranki <hemanthveeranki@gmail.com>
> create `next_character` function

- javascript/obstacle.js
- style/index.css
It was hard to see which obstacles will actually kill you, so this highlights them in red
> Stroke obstacles in red to make them easier to see/avoid

- style/index.css
Improve feel of starting game by making the circle clickable with better styles
> Start button cursor and color on hover

- hints/README.md
> fixed the typos in the readme file under /hints
